### ISSUE TITLE
Basic question: how to use downselect

### ISSUE THREAD

**Issue by sudeepy** [NREL/resstock#813]
Hi, I'm trying to run a simulation for all available housing stock in a particular county.

To do this, I thought I'm supposed to use downselect logic, as described here: https://resstock.readthedocs.io/en/latest/tutorial/setup_analysis_project.html#build-existing-model-1

I'm working off of the `project_national/national_upgrades.yml` project. The relevant part of my yaml file looks like this:

```
sampler:
  type: residential_quota_downselect
  args:
    n_datapoints: 1
    logic:
      - County|IN, Lake County
```

However, in `results_output.csv` the status is reported as "Invalid." This is surprising since the county is listed in `resources/options_lookup.tsv`. I've tried increasing `n_datapoints` but to no avail.

Am I misunderstanding how downselect logic works? My hypothesis is that the downselect logic is being applied after sampling which would cause this issue, but I'm not sure about that.

How can I run simulations for a particular county?

**Comment by sudeepy** [comment]
Circling back, since I was testing locally w/ `run_analysis.rb`, I think I tried up to 100 `n_datapoints`.

Thanks for the response @joseph-robertson and the links. I'm restarting my resstock investigations; so I'll take a look and follow up w/ my progress.

In the meantime, I want to make sure I understand what you're saying:

1. ResStock first performs sampling.
2. It then applies downselect filtering.
3. `buildstockbatch` supports resampling, which is the act of redoing sampling while also respecting the provided downselect filters from the previous step and is the behavior I'm looking for. `run_analysis.rb` does not support this.
4. ResStock performs the simulation.

Did I get that right?

**Comment by sudeepy** [comment]
@joseph-robertson I was able to successfully use downselect to run simulations for a specific county using `buildstockbatch ` on my local computer (M1 Macbook Pro). This is the sampler config in my project YML:

```
sampler:
  type: residential_quota_downselect
  args:
    n_datapoints: 1
    logic:
      - County|IN, Lake County
    resample: true
```

While this is great, the time to simulate just one datapoint was on the order of 30 min. Is this expected? Aside from caching weather data, is there anything else I can do to optimize this?
