### ISSUE TITLE
Calculate simple utility bills (enhancements)

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#890]
Call new `ReportUtilityBills` measure from OS-HPXML.

**Comment by ekpresent** [comment]
Good to see this basic capability added!

I think it will be much stronger once we can incorporate:
1. Geographically-specific utility rates. For example, if we could point to files with state-level rates.
2. TOU or other non-static rates.

I don't see significant benefit to doing bill calculations during the run versus after for static rates, but for more complicated rates like TOU rates or rates that have complicated dependencies (EV, PV, total consumption, etc.) it could be a big time saver.

**Comment by joseph-robertson** [comment]
For the second item above, you are probably referring to https://github.com/NREL/resstock/issues/988. We've divided our utility bill calculation work into 2 phases:

(1) Simple (fixed costs, marginal rates, PV compensation, etc.)
(2) Detailed (tariffs, TOU, tiered, etc.)

See https://github.com/NREL/OpenStudio-HPXML/issues/920 for more information.

**Comment by joseph-robertson** [comment]
My first cut at a design for enhancing our simple utility bill calculations. Here are several scenarios (i.e., possible options) I envision:

```
    utility_bills:
      - scenario_name: BillsSimpleStateAverage1
        # calc_type defaults to simple
        # no xxx_fixed_charge or xxx_marginal_rate means they get defaulted

      - scenario_name: BillsSimpleStateAverage2
        calc_type: simple
        # no xxx_fixed_charge or xxx_marginal_rate means they get defaulted

      - scenario_name: BillsSimpleSpecified1
        calc_type: simple
        elec_fixed_charge: 10.0
        elec_marginal_rate: 0.12
        # fixed charge / marginal rate applied to all samples

      - scenario_name: BillsSimpleSpecified2
        elec_fixed_charge: 10.0
        elec_marginal_rate: 0.12
        # calc_type defaults to simple
        # fixed charge / marginal rate applied to all samples

      - scenario_name: BillsSimpleSpecified3
        elec_simple_filepath: path/to/charges_and_rates.csv
        # calc_type defaults to simple
        # charges_and_rates.csv is lookup from state to fixed charges / marginal rates
        # this is to support #890 (elaina's suggestion)
```
