### ISSUE TITLE
Calculate detailed utility bills

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#988]
Pull in detailed utility bill calculation capabilities from OS-HPXML: https://github.com/NREL/OpenStudio-HPXML/pull/1092

**Comment by afontani** [comment]
Waiting on the OpenStudio-HPXML PR to get merged before pulling into ResStock.

**Comment by afontani** [comment]
@joseph-robertson : Are we able to pull this feature into ResStock now?

**Comment by joseph-robertson** [comment]
@afontani Yes we are.

**Comment by afontani** [comment]
The next steps are to design YAML and update the workflow generator in BuildStock-Batch. Possibly like Cambium. Considerations around multiple utilities and thus rates for a given geography.

**Comment by joseph-robertson** [comment]
My first cut at a design. Here are several scenarios I envision for a user requesting utility bills:

```
    utility_bills:
      - scenario_name: BillsSimpleStateAverage1
        calc_type: simple
        # no xxx_fixed_charge or xxx_marginal_rate means they get defaulted

      - scenario_name: BillsSimpleStateAverage2
        # calc_type defaults to simple
        # no xxx_fixed_charge or xxx_marginal_rate means they get defaulted

      - scenario_name: BillsSimpleSpecified1
        calc_type: simple
        elec_fixed_charge: 10.0
        elec_marginal_rate: 0.12
        # fixed charge / marginal rate applied to all samples

      - scenario_name: BillsSimpleSpecified2
        elec_fixed_charge: 10.0
        elec_marginal_rate: 0.12
        # calc_type defaults to simple
        # fixed charge / marginal rate applied to all samples

      - scenario_name: BillsDetailedEIAID
        calc_type: detailed
        # like emissions, i'm envisioning using a TSV as a lookup
        # from sampling this TSV you'd get, say, EIAID (utility ID)
        # utility ID would map to a specific tariff.json

      - scenario_name: BillsDetailedSpecified1
        calc_type: detailed
        elec_filepath: path/to/tariff.json
        # tariff.json is applied to all samples

      - scenario_name: BillsDetailedSpecified2
        elec_filepath: path/to/tariff.json
        # presence of this field means calc_type detailed
        # tariff.json is applied to all samples
```

@afontani @shorowit @ekpresent
